// Code generated by MockGen. DO NOT EDIT.
// Source: ./organization.go
//
// Generated by this command:
//
//	mockgen -typed -source=./organization.go -destination=../mocks/mock_organization_repository.go -package=mocks OrganizationRepositoryIface
//

// Package mocks is a generated GoMock package.
package mocks
